CREATE TABLE `Users` (
	`id` VARCHAR(255) NOT NULL UNIQUE,
	`name` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`role` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `Role` (
	`id` VARCHAR(255) NOT NULL UNIQUE,
	`name` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `Users_Role` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`user_id` VARCHAR(255) NOT NULL,
	`role_id` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `Driver` (
	`id` VARCHAR(255) NOT NULL UNIQUE,
	`driver_license` VARCHAR(255) NOT NULL,
	`age` VARCHAR(255) NOT NULL,
	`user_id` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `Car` (
	`id` VARCHAR(255) NOT NULL UNIQUE,
	`brand` VARCHAR(255) NOT NULL,
	`model` VARCHAR(255) NOT NULL,
	`plate` VARCHAR(255) NOT NULL,
	`driver_id` VARCHAR(255) NOT NULL,
	`image_url` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `Product` (
	`id` VARCHAR(255) NOT NULL UNIQUE,
	`name` VARCHAR(255) NOT NULL,
	`price` INTEGER NOT NULL,
	`quantity` INTEGER NOT NULL,
	`image_url` VARCHAR(255) NOT NULL,
	`category_id` VARCHAR(255) NOT NULL,
	`user_id` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE `Category` (
	`id` VARCHAR(255) NOT NULL UNIQUE,
	`name` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`id`)
);


ALTER TABLE `Users_Role`
ADD FOREIGN KEY(`user_id`) REFERENCES `Users`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Users_Role`
ADD FOREIGN KEY(`role_id`) REFERENCES `Role`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Driver`
ADD FOREIGN KEY(`user_id`) REFERENCES `Users`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Car`
ADD FOREIGN KEY(`driver_id`) REFERENCES `Driver`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Product`
ADD FOREIGN KEY(`category_id`) REFERENCES `Category`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Product`
ADD FOREIGN KEY(`user_id`) REFERENCES `Users`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;